service: serverless-haskell-test

resources: ${file(./resources/serverless.resources.yml)}

provider:
  name: aws
  runtime: haskell
  region: eu-central-1
  stage: dev

functions:
  getUser:
    name: serverless-test-get-user
    handler: serverless-haskell-test.get-user-exe
    events:
      - http:
          path: /{userId}
          method: get
  updateUser:
    name: serverless-test-update-user
    handler: serverless-haskell-test.update-user-exe
    events:
      - http:
          path: /{userId}
          method: put

custom:
  serverless-offline:
    port: 4000

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      seed: true
      inMemory: true
    seed:
      dev:
        sources:
          - table: haskell-users
            sources: [".seeds/users.json"]

package:
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-haskell
  - serverless-offline
